import instance from './assets/Instance.png';

export const instances = [
  {
    id: 1,
    title: "Meesho",
    description: "Testing on Meesho with device Samsung Galaxy S24 Android 13.0" ,
    image: instance,
    collaborators: {"tanisha@gmail.com":"Tanisha","raj@gmail.com":"Raj"},
    device:"Samsung Galaxy S24 Android 13.0",
    starred: false,
  },
  {
    id: 2,
    title: "PW",
    description: "Testing on PW with device Samsung Galaxy S24 Android 14.0 ",
    image: instance,
    collaborators: {"tanisha@gmail.com":"Tanisha","raj@gmail.com":"Raj","yash@gmail.com":"Yash"},
    device:"Samsung Galaxy S24 Android 14.0",
    starred: false,
  },
  {
    id: 3,
    title: "Zepto",
    description:  "Testing on Zepto with device Samsung Galaxy S24 Android 14.0 ",
    image: instance,
    collaborators: {"tanisha@gmail.com":"Tanisha","raj@gmail.com":"Raj","yash@gmail.com":"Yash"},
    device:"Samsung Galaxy S24 Android 14.0",
    starred: true,
  },
  {
    id: 4,
    title: "Cred",
    description: "Testing on Cred with device Samsung Galaxy S24 Android 14.0 ",
    image: instance,
    collaborators: {"raj@gmail.com":"Raj","yash@gmail.com":"Yash"},
    device:"Samsung Galaxy S24 Android 14.0",
    starred: false,
  },
  {
    id: 5,
    title: "PW",
    description: "Testing on PW with device Samsung Galaxy S24 Android 14.0.",
    image: instance,
    collaborators:{"yash@gmail.com":"Yash"},
    device:"Samsung Galaxy S24 Android 14.0",
    starred: true,
  },

  {
    id:6,
    title: "Meesho",
    description: "Testing on Meesho with device Samsung Galaxy S24 Android 13.0" ,
    image: instance,
    collaborators: {"raj@gmail.com":"Raj","yash@gmail.com":"Yash"},
    device:"Samsung Galaxy S24 Android 13.0",
    starred: true,
  },
  {
    id: 7,
    title: "PW",
    description: "Testing on PW with device Samsung Galaxy S24 Android 14.0 ",
    image: instance,
    collaborators:{"raj@gmail.com":"Raj","yash@gmail.com":"Yash"},
    device:"Samsung Galaxy S24 Android 14.0",
    starred: false,
  },
  {
    id: 8,
    title: "Zepto",
    description:  "Testing on Zepto with device Samsung Galaxy S24 Android 14.0 ",
    image: instance,
    collaborators:{"raj@gmail.com":"Raj","yash@gmail.com":"Yash"},
    device:"Samsung Galaxy S24 Android 14.0",
    starred: true,
  },
  {
    id: 9,
    title: "Cred",
    description: "Testing on Cred with device Samsung Galaxy S24 Android 14.0 ",
    image: instance,
    collaborators:{"raj@gmail.com":"Raj","yash@gmail.com":"Yash"},
    device:"Samsung Galaxy S24 Android 14.0",
    starred: false,
  },
  {
    id: 10,
    title: "PW",
    description: "Testing on PW with device Samsung Galaxy S24 Android 14.0.",
    image: instance,
    collaborators: {"raj@gmail.com":"Raj","yash@gmail.com":"Yash"},
    device:"Samsung Galaxy S24 Android 14.0",
    starred: false,
  },
];
